---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: gitops-demo-policies
  namespace: rhacm-policies
  annotations:
    apps.open-cluster-management.io/reconcile-rate: medium
spec:
  type: GitHub
  pathname: https://github.com/josgonza-rh/rhacm-gitops.git